# Generated by Django 6.0.2 on 2026-03-31 18:03

from django.db import migrations, models


def populate_sizes(apps, schema_editor):
    RAGSource = apps.get_model("advisor", "RAGSource")
    RAGChunk = apps.get_model("advisor", "RAGChunk")

    for chunk in RAGChunk.objects.all().only("id", "content"):
        content = chunk.content or ""
        chunk.chunk_size_bytes = len(content.encode("utf-8"))
        chunk.save(update_fields=["chunk_size_bytes"])

    storage = RAGSource._meta.get_field("uploaded_file").storage
    for source in RAGSource.objects.all().only("id", "uploaded_file", "source_size_bytes"):
        file_name = source.uploaded_file.name
        if file_name and storage.exists(file_name):
            source.source_size_bytes = storage.size(file_name)
            source.save(update_fields=["source_size_bytes"])


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_conversationhistory_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ragsource',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameIndex(
            model_name='ragchunk',
            new_name='advisor_rag_source__835401_idx',
            old_name='advisor_ragc_source__4f4ecc_idx',
        ),
        migrations.AddField(
            model_name='ragchunk',
            name='chunk_size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ragsource',
            name='first_author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ragsource',
            name='has_multiple_authors',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
        migrations.AddField(
            model_name='ragsource',
            name='source_size_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.RunPython(populate_sizes, migrations.RunPython.noop),
    ]
